### ISSUE TITLE
Android 14 Support

### ISSUE THREAD

**Issue by JeromeCHA** [DeployGate/deploygate-android-sdk#71]
When changing the targetSdk to 34, due to [new security restrictions](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported) with broadcasts, we have the following error :

```
java.lang.RuntimeException: Unable to get provider com.deploygate.sdk.DeployGateProvider: java.lang.SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
    at android.app.ActivityThread.installProvider(ActivityThread.java:7769)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:7275)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6982)
    at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8176)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
    at android.os.Parcel.createException(Parcel.java:3041)
    at android.os.Parcel.readException(Parcel.java:3024)
    at android.os.Parcel.readException(Parcel.java:2966)
    at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5668)
    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
    at com.deploygate.sdk.DeployGate.prepareBroadcastReceiver(DeployGate.java:262)
    at com.deploygate.sdk.DeployGate.<init>(DeployGate.java:234)
    at com.deploygate.sdk.DeployGate.install(DeployGate.java:580)
    at com.deploygate.sdk.DeployGate.install(DeployGate.java:539)
    at com.deploygate.sdk.DeployGate.install(DeployGate.java:513)
    at com.deploygate.sdk.DeployGateProvider.onCreate(DeployGateProvider.java:15)
    at android.content.ContentProvider.attachInfo(ContentProvider.java:2619)
    at android.content.ContentProvider.attachInfo(ContentProvider.java:2589)
    at android.app.ActivityThread.installProvider(ActivityThread.java:7764)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:7275) 
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6982) 
    at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loopOnce(Looper.java:205) 
    at android.os.Looper.loop(Looper.java:294) 
    at android.app.ActivityThread.main(ActivityThread.java:8176) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
Caused by: android.os.RemoteException: Remote stack trace:
    at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13895)
    at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2563)
    at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2708)
    at android.os.Binder.execTransactInternal(Binder.java:1339)
    at android.os.Binder.execTransact(Binder.java:1275)
```

It looks like `RECEIVER_EXPORTED` or `RECEIVER_NOT_EXPORTED` flag must be added here.
https://github.com/DeployGate/deploygate-android-sdk/blob/bd0489687d8258533095a38de811901862e42e76/sdk/src/main/java/com/deploygate/sdk/DeployGate.java#L262C9-L262C69

**Comment by jmatsu** [comment]
Thank you for your reporting. We'll check this.

**Comment by jmatsu** [comment]
@JeromeCHA 
We have released version 4.5.0 to support target sdk 34. Could you please check it?

https://central.sonatype.com/artifact/com.deploygate/sdk/4.5.0

**Comment by jmatsu** [comment]
Please feel free to reopen this issue and let us know if you still have any problem. Thanks for your reporting!
